drop table if exists eventlog.alembic_version;
drop table if exists eventlog.asset_check_executions;
drop table if exists eventlog.asset_daemon_asset_evaluations;
drop table if exists eventlog.asset_event_tags cascade;
drop table if exists eventlog.event_logs cascade;
drop table if exists eventlog.asset_keys;
drop table if exists eventlog.bulk_actions;
drop table if exists eventlog.concurrency_slots cascade;
drop table if exists eventlog.daemon_heartbeats;
drop table if exists eventlog.dynamic_partitions cascade;
drop table if exists eventlog.event_logs;
drop table if exists eventlog.instance_info;
drop table if exists eventlog.instigators;
drop table if exists eventlog.job_ticks;
drop table if exists eventlog.jobs;
drop table if exists eventlog.kvs;
drop table if exists eventlog.pending_steps;
drop table if exists eventlog.run_tags cascade;
drop table if exists eventlog.runs cascade;
drop table if exists eventlog.secondary_indexes;
drop table if exists eventlog.snapshots cascade;